basic.showArrow(ArrowNames.NorthWest)
basic.pause(5000)
music.playMelody("F C5 F C5 F C5 F C5 ", 120)
TobbieII.dance(3)
basic.showArrow(ArrowNames.NorthEast)
TobbieII.forward()
basic.pause(5000)
TobbieII.stopwalk()
